#

pluginName = org.bpy.electronic.grafcet Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Model_type = Model
_UI_Grafcet_type = Grafcet
_UI_GrafcetEntryPoint_type = Entry Point
_UI_GrafcetElement_type = Element
_UI_Report_type = Report
_UI_TransitionOnly_type = Transition Only
_UI_ActionOnly_type = Action Only
_UI_TransitionAction_type = Transition Action
_UI_GrafcetStep_type = Step
_UI_EndElement_type = End Element
_UI_GrafcetEntry_type = Entry
_UI_GrafcetEnded_type = Ended
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Model_grafcetEntry_feature = Grafcet Entry
_UI_Model_grafcetEnded_feature = Grafcet Ended
_UI_Model_grafcets_feature = Grafcets
_UI_Model_sequencerPath_feature = Sequencer Path
_UI_Grafcet_entrypoint_feature = Entrypoint
_UI_Grafcet_name_feature = Name
_UI_Grafcet_order_feature = Order
_UI_Grafcet_next_feature = Next
_UI_Grafcet_autorun_feature = Autorun
_UI_Grafcet_end_feature = End
_UI_GrafcetEntryPoint_step_feature = Step
_UI_GrafcetEntryPoint_name_feature = Name
_UI_GrafcetElement_name_feature = Name
_UI_GrafcetElement_comment_feature = Comment
_UI_GrafcetElement_nextStep_feature = Next Step
_UI_TransitionOnly_transitionFct_feature = Transition Fct
_UI_ActionOnly_actionFct_feature = Action Fct
_UI_TransitionAction_transitionFct_feature = Transition Fct
_UI_TransitionAction_actionFct_feature = Action Fct
_UI_GrafcetStep_elements_feature = Elements
_UI_GrafcetStep_name_feature = Name
_UI_GrafcetStep_comment_feature = Comment
_UI_GrafcetEntry_startingGrafcet_feature = Starting Grafcet
_UI_Unknown_feature = Unspecified

_UI_Grafcet_entryPoint_feature = Entry Point
_UI_Grafcet_steps_feature = Steps
_UI_Grafcet_grafcets_feature = Grafcets
_UI_GrafcetStep_grafcets_feature = Grafcets
_UI_TransitionAction_name_feature = Name
_UI_TransitionAction_comment_feature = Comment
_UI_GrafcetStep_description_feature = Description
_UI_Action_type = Action
_UI_Transition_type = Transition
_UI_PassThrough_type = Pass Through
_UI_Action_actionFct_feature = Action Fct
_UI_Transition_transitionFct_feature = Transition Fct
_UI_PassThrough_transitionFct_feature = Transition Fct
_UI_Report_label_feature = Label
_UI_GrafcetStep_startingGraphicalPoint_feature = Starting Graphical Point
_UI_GrafcetConnector_type = Connector
_UI_GrafcetStep_entryConnector_feature = Entry Connector
_UI_GrafcetConnector_elements_feature = Elements
_UI_GrafcetConnector_name_feature = Name
_UI_Grafcet_description_feature = Description
_UI_GrafcetConnector_grafcetelement_feature = Grafcetelement
_UI_GrafcetConnector_grafcetElements_feature = Grafcet Elements
_UI_TransitionAction_nextStep_feature = Next Step
_UI_GrafcetStep_grafcetElements_feature = Grafcet Elements
_UI_GrafcetElement_location_feature = Location
_UI_Grafcet_reports_feature = Reports
_UI_GrafcetElement_nextReportStep_feature = Next Report Step
_UI_Report_nextStep_feature = Next Step
_UI_GrafcetEntryPoint_report_feature = Report
_UI_Model_projectName_feature = Project Name
_UI_Model_description_feature = Description
_UI_GrafcetElement_uuid_feature = Uuid
