/**
 */
package org.bpy.electronic.ArduinoGrafcet.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.bpy.electronic.ArduinoGrafcet.util.GrafcetAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class GrafcetItemProviderAdapterFactory extends GrafcetAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public GrafcetItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.bpy.electronic.ArduinoGrafcet.Model} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelItemProvider modelItemProvider;

	/**
	 * This creates an adapter for a {@link org.bpy.electronic.ArduinoGrafcet.Model}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelAdapter() {
		if (modelItemProvider == null) {
			modelItemProvider = new ModelItemProvider(this);
		}

		return modelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.bpy.electronic.ArduinoGrafcet.Grafcet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GrafcetItemProvider grafcetItemProvider;

	/**
	 * This creates an adapter for a {@link org.bpy.electronic.ArduinoGrafcet.Grafcet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGrafcetAdapter() {
		if (grafcetItemProvider == null) {
			grafcetItemProvider = new GrafcetItemProvider(this);
		}

		return grafcetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.bpy.electronic.ArduinoGrafcet.GrafcetEntryPoint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GrafcetEntryPointItemProvider grafcetEntryPointItemProvider;

	/**
	 * This creates an adapter for a {@link org.bpy.electronic.ArduinoGrafcet.GrafcetEntryPoint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGrafcetEntryPointAdapter() {
		if (grafcetEntryPointItemProvider == null) {
			grafcetEntryPointItemProvider = new GrafcetEntryPointItemProvider(this);
		}

		return grafcetEntryPointItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.bpy.electronic.ArduinoGrafcet.TransitionAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransitionActionItemProvider transitionActionItemProvider;

	/**
	 * This creates an adapter for a {@link org.bpy.electronic.ArduinoGrafcet.TransitionAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransitionActionAdapter() {
		if (transitionActionItemProvider == null) {
			transitionActionItemProvider = new TransitionActionItemProvider(this);
		}

		return transitionActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.bpy.electronic.ArduinoGrafcet.GrafcetStep} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GrafcetStepItemProvider grafcetStepItemProvider;

	/**
	 * This creates an adapter for a {@link org.bpy.electronic.ArduinoGrafcet.GrafcetStep}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGrafcetStepAdapter() {
		if (grafcetStepItemProvider == null) {
			grafcetStepItemProvider = new GrafcetStepItemProvider(this);
		}

		return grafcetStepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.bpy.electronic.ArduinoGrafcet.GrafcetEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GrafcetEntryItemProvider grafcetEntryItemProvider;

	/**
	 * This creates an adapter for a {@link org.bpy.electronic.ArduinoGrafcet.GrafcetEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGrafcetEntryAdapter() {
		if (grafcetEntryItemProvider == null) {
			grafcetEntryItemProvider = new GrafcetEntryItemProvider(this);
		}

		return grafcetEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.bpy.electronic.ArduinoGrafcet.GrafcetEnded} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GrafcetEndedItemProvider grafcetEndedItemProvider;

	/**
	 * This creates an adapter for a {@link org.bpy.electronic.ArduinoGrafcet.GrafcetEnded}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGrafcetEndedAdapter() {
		if (grafcetEndedItemProvider == null) {
			grafcetEndedItemProvider = new GrafcetEndedItemProvider(this);
		}

		return grafcetEndedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.bpy.electronic.ArduinoGrafcet.Action} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActionItemProvider actionItemProvider;

	/**
	 * This creates an adapter for a {@link org.bpy.electronic.ArduinoGrafcet.Action}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActionAdapter() {
		if (actionItemProvider == null) {
			actionItemProvider = new ActionItemProvider(this);
		}

		return actionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.bpy.electronic.ArduinoGrafcet.Transition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransitionItemProvider transitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.bpy.electronic.ArduinoGrafcet.Transition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransitionAdapter() {
		if (transitionItemProvider == null) {
			transitionItemProvider = new TransitionItemProvider(this);
		}

		return transitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.bpy.electronic.ArduinoGrafcet.PassThrough} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PassThroughItemProvider passThroughItemProvider;

	/**
	 * This creates an adapter for a {@link org.bpy.electronic.ArduinoGrafcet.PassThrough}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPassThroughAdapter() {
		if (passThroughItemProvider == null) {
			passThroughItemProvider = new PassThroughItemProvider(this);
		}

		return passThroughItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.bpy.electronic.ArduinoGrafcet.Report} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReportItemProvider reportItemProvider;

	/**
	 * This creates an adapter for a {@link org.bpy.electronic.ArduinoGrafcet.Report}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReportAdapter() {
		if (reportItemProvider == null) {
			reportItemProvider = new ReportItemProvider(this);
		}

		return reportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.bpy.electronic.ArduinoGrafcet.GrafcetConnector} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GrafcetConnectorItemProvider grafcetConnectorItemProvider;

	/**
	 * This creates an adapter for a {@link org.bpy.electronic.ArduinoGrafcet.GrafcetConnector}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGrafcetConnectorAdapter() {
		if (grafcetConnectorItemProvider == null) {
			grafcetConnectorItemProvider = new GrafcetConnectorItemProvider(this);
		}

		return grafcetConnectorItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (modelItemProvider != null) modelItemProvider.dispose();
		if (grafcetItemProvider != null) grafcetItemProvider.dispose();
		if (grafcetEntryPointItemProvider != null) grafcetEntryPointItemProvider.dispose();
		if (transitionActionItemProvider != null) transitionActionItemProvider.dispose();
		if (grafcetStepItemProvider != null) grafcetStepItemProvider.dispose();
		if (grafcetEntryItemProvider != null) grafcetEntryItemProvider.dispose();
		if (grafcetEndedItemProvider != null) grafcetEndedItemProvider.dispose();
		if (actionItemProvider != null) actionItemProvider.dispose();
		if (transitionItemProvider != null) transitionItemProvider.dispose();
		if (passThroughItemProvider != null) passThroughItemProvider.dispose();
		if (reportItemProvider != null) reportItemProvider.dispose();
		if (grafcetConnectorItemProvider != null) grafcetConnectorItemProvider.dispose();
	}

}
